main.o: main.c pos.h list.h buffer.h ui.h buffers.h
ncurses.o: ncurses.c ncurses.h
ui.o: ui.c pos.h ncurses.h list.h buffer.h ui.h motion.h keys.h buffers.h \
 io.h map.h
mem.o: mem.c mem.h
keys.o: keys.c pos.h list.h buffer.h ui.h motion.h keys.h ncurses.h mem.h \
 cmds.h prompt.h map.h io.h buffers.h config.h
cmds.o: cmds.c cmds.h pos.h list.h buffer.h ui.h buffers.h external.h \
 mem.h
buffer.o: buffer.c pos.h list.h buffer.h mem.h
list.o: list.c pos.h list.h mem.h str.h
buffers.o: buffers.c pos.h list.h buffer.h buffers.h mem.h ui.h
motion.o: motion.c pos.h list.h buffer.h motion.h ui.h io.h map.h str.h \
 prompt.h
external.o: external.c mem.h ui.h external.h
str.o: str.c str.h
prompt.o: prompt.c prompt.h ncurses.h io.h map.h mem.h
io.o: io.c ncurses.h mem.h io.h map.h
pos.o: pos.c pos.h
