main.o: main.c pos.h region.h list.h buffer.h bufmode.h yank.h retain.h \
  ui.h window.h windows.h
ncurses.o: ncurses.c ncurses.h macros.h
ui.o: ui.c pos.h ncurses.h region.h list.h buffer.h bufmode.h yank.h \
  retain.h window.h windows.h io.h ui.h motion.h word.h cmds.h keys.h \
  buffers.h mem.h str.h indent.h
mem.o: mem.c mem.h
keys.o: keys.c pos.h region.h list.h buffer.h bufmode.h yank.h retain.h \
  window.h windows.h range.h io.h ui.h motion.h word.h cmds.h keys.h \
  ncurses.h mem.h prompt.h map.h str.h external.h ctags.h parse_cmd.h \
  indent.h buffers.h config.h
cmds.o: cmds.c range.h cmds.h pos.h region.h list.h buffer.h bufmode.h \
  yank.h retain.h io.h ui.h buffers.h external.h mem.h parse_cmd.h str.h \
  ncurses.h window.h windows.h
buffer.o: buffer.c pos.h region.h list.h buffer.h bufmode.h yank.h \
  retain.h mem.h macros.h ncurses.h str.h buffers.h indent.h
list.o: list.c pos.h region.h range.h list.h mem.h str.h macros.h word.h
motion.o: motion.c pos.h region.h list.h buffer.h bufmode.h yank.h \
  retain.h window.h motion.h ui.h io.h str.h prompt.h word.h macros.h
external.o: external.c mem.h ui.h pos.h region.h list.h external.h
str.o: str.c str.h mem.h
prompt.o: prompt.c prompt.h ncurses.h io.h bufmode.h mem.h
io.o: io.c ncurses.h mem.h io.h bufmode.h map.h str.h
yank.o: yank.c pos.h region.h list.h yank.h mem.h retain.h
pos.o: pos.c pos.h
region.o: region.c pos.h region.h
retain.o: retain.c retain.h
range.o: range.c pos.h region.h list.h buffer.h bufmode.h yank.h retain.h \
  buffers.h window.h windows.h range.h
parse_cmd.o: parse_cmd.c mem.h pos.h region.h list.h buffer.h bufmode.h \
  yank.h retain.h buffers.h range.h cmds.h window.h windows.h str.h \
  parse_cmd.h config_cmds.h
word.o: word.c pos.h region.h list.h word.h
buffers.o: buffers.c pos.h region.h list.h buffer.h bufmode.h yank.h \
  retain.h buffers.h window.h windows.h
window.o: window.c mem.h macros.h pos.h region.h list.h buffer.h \
  bufmode.h yank.h retain.h window.h ncurses.h
windows.o: windows.c pos.h region.h list.h buffer.h bufmode.h yank.h \
  retain.h window.h windows.h ui.h
ctags.o: ctags.c mem.h ctags.h
indent.o: indent.c pos.h region.h list.h indent.h
