main.o: main.c pos.h region.h list.h buffer.h bufmode.h ui.h buffers.h
ncurses.o: ncurses.c ncurses.h macros.h
ui.o: ui.c pos.h ncurses.h region.h list.h buffer.h bufmode.h ui.h \
 motion.h io.h map.h keys.h buffers.h
mem.o: mem.c mem.h
keys.o: keys.c pos.h region.h list.h buffer.h bufmode.h ui.h motion.h \
 io.h map.h keys.h ncurses.h mem.h cmds.h prompt.h buffers.h config.h
cmds.o: cmds.c cmds.h pos.h region.h list.h buffer.h bufmode.h ui.h \
 buffers.h external.h mem.h
buffer.o: buffer.c pos.h region.h list.h buffer.h bufmode.h mem.h \
 macros.h ncurses.h str.h
list.o: list.c pos.h region.h list.h mem.h str.h
buffers.o: buffers.c pos.h region.h list.h buffer.h bufmode.h buffers.h \
 mem.h ui.h
motion.o: motion.c pos.h region.h list.h buffer.h bufmode.h motion.h ui.h \
 io.h map.h str.h prompt.h
external.o: external.c mem.h ui.h external.h
str.o: str.c str.h
prompt.o: prompt.c prompt.h ncurses.h io.h map.h mem.h
io.o: io.c ncurses.h mem.h io.h map.h
pos.o: pos.c pos.h
region.o: region.c pos.h region.h
